[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/db.json"
  status = 302

[[headers]]
 
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"