[build]
  publish = "public"

[[redirects]]
  from = "/api/"
  to = "/db.json"
  status = 302
  headers = { Access-Control-Allow-Origin = "*", Authorization = "Bearer api-key"}

[[headers]]
 
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Authorization = "Bearer api-key"