[build]
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/db.json"
  status = 200
  headers = { Access-Control-Allow-Origin = "*", Authorization = "Bearer api-key"}

[[headers]]
 
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Authorization = "Bearer api-key"